name: OAS

on:
  push:
    branches:
      - main
      - stable/*
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  oas:
    name: Checks
    uses: maykinmedia/open-api-workflows/.github/workflows/oas.yml@v5
    with:
      python-version: '3.12'
      apt-packages: ''
      django-settings-module: opentaak.conf.ci
      oas-generate-command: ./bin/generate_api_schema.sh
      schema-path: src/opentaak/api/openapi.yaml
      oas-artifact-name: opentaak-api-oas
      node-version-file: '.nvmrc'
      spectral-version: '^6.15.0'
      openapi-to-postman-version: '^5.0.0'
      postman-artifact-name: opentaak-api-postman-collection
      openapi-generator-version: '^2.20.0'
